name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set RELEASE_VERSION environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Decode signing key
        run: echo ${{ secrets.SIGNING_KEY_ENCRYPTED_BASE64 }} | base64 -d > library/encrypted_secret.gpg

      - name: Decrypt signing key
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SIGNING_KEY_SECRET_PASS_PHRASE }}" --output library/decrypted_secret.gpg library/encrypted_secret.gpg

      - name: Publish on Maven Central
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: publish
            -Psigning.secretKeyRingFile=decrypted_secret.gpg
            -Psigning.keyId=${{secrets.SIGNING_KEY_ID}}
            -Psigning.password=${{secrets.SIGNING_PASSWORD}}
            -Psonatype_username=${{secrets.SONATYPE_USERNAME}}
            -Psonatype_password=${{secrets.SONATYPE_PASSWORD}}